/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

import modelo.Pessoa;

/**
 *
 * @author tuler
 */
public class ViewPrincipal extends javax.swing.JFrame {
    
    /**
     * Creates new form ViewStart
     */
    public ViewPrincipal() {
        initComponents();
    }

    public ViewPrincipal(Pessoa pessoa) {
        this.pessoa = pessoa;
        initComponents();
        this.setLocationRelativeTo(null);
        this.setSize(500, 400);
        this.setResizable(false);
        //System.out.println(pessoa.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpDesktop = new javax.swing.JDesktopPane();
        menu = new javax.swing.JMenuBar();
        menuUsuario = new javax.swing.JMenu();
        subMenuPerfil = new javax.swing.JMenu();
        opInfo = new javax.swing.JMenuItem();
        opStatus = new javax.swing.JMenuItem();
        subMenuContatos = new javax.swing.JMenu();
        opStatusContatos = new javax.swing.JMenuItem();
        opLogout = new javax.swing.JMenuItem();
        menuRecado = new javax.swing.JMenu();
        opEnviar = new javax.swing.JMenuItem();
        opReceber = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("sPager");
        setLocationByPlatform(true);

        javax.swing.GroupLayout dpDesktopLayout = new javax.swing.GroupLayout(dpDesktop);
        dpDesktop.setLayout(dpDesktopLayout);
        dpDesktopLayout.setHorizontalGroup(
            dpDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 404, Short.MAX_VALUE)
        );
        dpDesktopLayout.setVerticalGroup(
            dpDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 306, Short.MAX_VALUE)
        );

        menuUsuario.setText("Usuario");

        subMenuPerfil.setText("Perfil");

        opInfo.setText("Informações");
        opInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opInfoActionPerformed(evt);
            }
        });
        subMenuPerfil.add(opInfo);

        opStatus.setText("Status");
        opStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opStatusActionPerformed(evt);
            }
        });
        subMenuPerfil.add(opStatus);

        menuUsuario.add(subMenuPerfil);

        subMenuContatos.setText("Contatos");

        opStatusContatos.setText("Status");
        opStatusContatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opStatusContatosActionPerformed(evt);
            }
        });
        subMenuContatos.add(opStatusContatos);

        menuUsuario.add(subMenuContatos);

        opLogout.setText("Logout");
        opLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opLogoutActionPerformed(evt);
            }
        });
        menuUsuario.add(opLogout);

        menu.add(menuUsuario);

        menuRecado.setText("Recado");

        opEnviar.setText("Enviar");
        opEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opEnviarActionPerformed(evt);
            }
        });
        menuRecado.add(opEnviar);

        opReceber.setText("Receber");
        opReceber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opReceberActionPerformed(evt);
            }
        });
        menuRecado.add(opReceber);

        menu.add(menuRecado);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpDesktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpDesktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opLogoutActionPerformed
        closeWiewPrincipal();
    }//GEN-LAST:event_opLogoutActionPerformed

    private void opInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opInfoActionPerformed
        ViewPerfil viewPessoa = new ViewPerfil(this.pessoa);
        dpDesktop.add(viewPessoa);
        viewPessoa.setVisible(true);
    }//GEN-LAST:event_opInfoActionPerformed

    private void opStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opStatusActionPerformed
        ViewSituacao viewSituacao = new ViewSituacao(this.pessoa);
        dpDesktop.add(viewSituacao);
        viewSituacao.setVisible(true);
    }//GEN-LAST:event_opStatusActionPerformed

    private void opEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opEnviarActionPerformed
        ViewEnviaRecado viewEnviaRecado = new ViewEnviaRecado(this.pessoa);
        dpDesktop.add(viewEnviaRecado);
        viewEnviaRecado.setVisible(true);
    }//GEN-LAST:event_opEnviarActionPerformed

    private void opReceberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opReceberActionPerformed
        ViewCaixaRecados viewCaixaRecados = new ViewCaixaRecados(this.pessoa);
        dpDesktop.add(viewCaixaRecados);
        viewCaixaRecados.setVisible(true);
    }//GEN-LAST:event_opReceberActionPerformed

    private void opStatusContatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opStatusContatosActionPerformed
        ViewContatos viewContatos = new ViewContatos(this.pessoa);
        dpDesktop.add(viewContatos);
        viewContatos.setVisible(true);
    }//GEN-LAST:event_opStatusContatosActionPerformed

    protected void closeWiewPrincipal(){
        this.dispose();
        ViewInicial viewInicial = new ViewInicial();
        viewInicial.setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dpDesktop;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenu menuRecado;
    private javax.swing.JMenu menuUsuario;
    private javax.swing.JMenuItem opEnviar;
    private javax.swing.JMenuItem opInfo;
    private javax.swing.JMenuItem opLogout;
    private javax.swing.JMenuItem opReceber;
    private javax.swing.JMenuItem opStatus;
    private javax.swing.JMenuItem opStatusContatos;
    private javax.swing.JMenu subMenuContatos;
    private javax.swing.JMenu subMenuPerfil;
    // End of variables declaration//GEN-END:variables
    private Pessoa pessoa;
}
